#!/bin/sh
backupdir="/etc /root"
filename="dar_$(date '+%y%m%d').tar.gz"

# Архивируем
tar -cvzf  "$filename" $backupdir --exclude="*.tar.gz"..

#  Бакапим на сервер (IP 192.168.0.1)
smbclient -U User //192.168.0.1/arhivserver$ "Password" <<EOF
cd /linux
put "$filename"
exit
EOF

rm "$filename"
